name: Java CI Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
                 
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Upload release the-unsafe
        uses: actions/upload-artifact@v4
        if: ${{ !github.head_ref }}
        with:
          name: the-unsafe
          path: build/libs/the-unsafe.jar
